### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by LDYang694** [changwoonchoi/3Doodle#1]
Hello, thank you for your outstanding work. When will the code be open-sourced?

**Comment by changwoonchoi** [comment]
Hello, thank you for your interest to our work!
I am working on the other project right now, and I am aiming to finish the project before mid June.
So, the source codes of 3Doodle would be available around mid June!

**Comment by wqdong8** [comment]
Very nice work! loooooking forward to your code.

**Comment by LDYang694** [comment]
Hi, how is your ongoing project going? Still looking forward to your open source code!

**Comment by changwoonchoi** [comment]
Hi all, we are planning to release source codes and example data within this week. Sorry for delay :pray:

**Comment by changwoonchoi** [comment]
Thank you for waiting! We released the source code. Please refer to it.
