### ISSUE TITLE
whether the point clouds .npy file of each object is used for training???

### ISSUE THREAD

**Issue by DanielCho-HK** [changwoonchoi/3Doodle#10]
Dear authors, I would like to ask whether the .npy file is used for training? Since we find that the training code only reads multi-view test images of each object. We can't find the code for reading .npy point cloud data. I am confused about it. Wish you can give me some guidance. Thank you for your help.

**Comment by DanielCho-HK** [comment]
If the provided .npy file is not used, where is the code for computing the 3D point clouds using the multi-view images and the corresponding camera pose information given by the .json file? Thank you so much.

**Comment by changwoonchoi** [comment]
Hi, we read SfM point cloud at here.
https://github.com/changwoonchoi/3Doodle/blob/fc20702c0c04586639ac0de17bfef1159e3f950b/src/doodle3d/dataset/base.py#L82

**Comment by DanielCho-HK** [comment]
> Hi, we read SfM point cloud at here.
> 
> https://github.com/changwoonchoi/3Doodle/blob/fc20702c0c04586639ac0de17bfef1159e3f950b/src/doodle3d/dataset/base.py#L82

Thank you author. I would like to ask whether the file all.npy is used for training. Since when I delete this file, the code can still runs for training.

**Comment by changwoonchoi** [comment]
In that case (when you don't have point cloud file, i.e. `dataset.init_points is None`), our code randomly sample control points to initialize.
https://github.com/changwoonchoi/3Doodle/blob/fc20702c0c04586639ac0de17bfef1159e3f950b/src/doodle3d/curve/network.py#L156

I just added one CLI print line for that case.
