### ISSUE TITLE
why not set the batchsize > 1?

### ISSUE THREAD

**Issue by Yovecent** [changwoonchoi/3Doodle#14]
I have a question, why not set the batch size > 1？Is that because there is not sufficient VRAM？

**Comment by changwoonchoi** [comment]
Hi, basically you can increase the batch size if you want. But I didn't test with batch size > 1, so you may need to check code if there is no bug with batch size > 1. (Also you may need to modify learning rate as well.)

**Comment by Yovecent** [comment]
> Hi, basically you can increase the batch size if you want. But I didn't test with batch size > 1, so you may need to check code if there is no bug with batch size > 1. (Also you may need to modify learning rate as well.)

really thanks!
