### ISSUE TITLE
License

### ISSUE THREAD

**Issue by n1ckfg** [changwoonchoi/3Doodle#4]
Saw your Siggraph talk, this looks great! Can you add your license info?

**Comment by changwoonchoi** [comment]
Hi, thank you for your interest to our work! Let me discuss about the license with the coauthors and I'll update the license info.

**Comment by changwoonchoi** [comment]
Hi, we added license info. Please refer to it. Basically, our code is MIT, but you may need to take care of the license of the libraries that we use.
