### ISSUE TITLE
Save the sketch.

### ISSUE THREAD

**Issue by mritunjoyh** [changwoonchoi/3Doodle#7]
Hi,
Is there a way to save the sketch as point cloud (points will be in the line) or as an obj file?

**Comment by wqdong8** [comment]
+1

**Comment by changwoonchoi** [comment]
Hi, if you want to obtain points along the Bézier curve (given control points), you can try this approach.
```
def bezier_curve_3d(points: torch.Tensor, num_points: int = 100):
    """Evaluates a cubic Bezier curve at `num_points` points in 3D.
    """
    p0, p1, p2, p3 = points[0], points[1], points[2], points[3]
    t = torch.linspace(0, 1, num_points, device=points.device).unsqueeze(1)
    points = (1-t)**3 * p0 + 3*(1-t)**2 * t * p1 + 3*(1-t) * t**2 * p2 + t**3 * p3
    return points
   ```
Then, you can save this points with format that you prefer.

**Comment by mritunjoyh** [comment]
Thanks that worked.

**Comment by melon-bubble** [comment]
@mritunjoyh Hello! Can you share the scripts about how to save the sketch as an obj file？My coding skills are rather weak. I have tried many times but still failed to save obj successfully. Thanks a lot!
